/*
 ~ CHECK RAMPA - v2.3

 ~      Copyright (C) 2014 Core3 Software, Inc.

 ~ Licensed under the Apache License, Version 2.0 (the "License");
 ~ you may not use this file except in compliance with the License.
 ~ You may obtain a copy of the License at

 ~   http://www.apache.org/licenses/LICENSE-2.0

 ~ Unless required by applicable law or agreed to in writing, software
 ~ distributed under the License is distributed on an "AS IS" BASIS,
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 ~ See the License for the specific language governing permissions and
 ~ limitations under the License.


 ~  @Author Lucas "C0rey" Cavalcante
 ~  @Version 2.3.0
 ~
 */

package com.core3soft.checkrampa;

import android.app.ActionBar;
import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.EditText;
import android.widget.Toast;


public class Main extends Activity {
    // widgets
    EditText eHeight, eLength;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        // actionbar
        ActionBar actionBar = getActionBar();
        if (actionBar != null) {
            actionBar.setTitle(getResources().getString(R.string.app_name));
            actionBar.setDisplayHomeAsUpEnabled(true);
            actionBar.show();
        }

        // findViews
        eHeight = (EditText) findViewById(R.id.height);
        eLength = (EditText) findViewById(R.id.length);
        // handler -> onclicklistener
        findViewById(R.id.button_checkramp).setOnClickListener(buttonHandler);

    }

    @Override
    public void onBackPressed() {
        finish();
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // inflate menu *Generated by Android Studio
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case R.id.action_about:
                // Start new activity on click in item menu 'about'
                startActivity(new Intent(Main.this, About.class));
                return true;
            case R.id.action_exit:
                // close app
                finish();
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }

    View.OnClickListener buttonHandler = new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            if (!eHeight.getText().toString().isEmpty() && !eLength.getText().toString().isEmpty()) {
                // start new activity sending extra informations to activity result
                startActivity(new Intent(Main.this, Result.class).putExtra("Altura", eHeight.getText().toString())
                    .putExtra("Comprimento", eLength.getText().toString()));
            } else SendMessage("Você deixou um campo em branco.");
        }
    };

    public void SendMessage(String msg) {
        // Send toast message to user
        Toast toast = Toast.makeText(getApplicationContext(), msg, Toast.LENGTH_SHORT);
        toast.show();
    }
}
